### PR TITLE
[ENH] Fix argument types in argparser

### LINKED ISSUE #15: Accept None instead of empty strings for skipped arguments
A number of arguments expect empty strings if you don't want to provide them and explicitly check against those in such a way that `None` breaks things.

### PR DESCRIPTION
**Pull request by tsalo**
Closes #15.

Changes proposed:
- Add functions to support better argument type checks (e.g., existence of file or folder).
- Simplify exceptions in AROMA workflow.
- Use `None` instead of `""` when not providing an argument.

### CODE REVIEW

**Comment by tsalo** [comment]
There may be a better approach to the type checks using `pathlib`. I'm looking into that now, although it will also impact our minimum Python version.

**Comment by tsalo** [comment]
It looks like we need separate functions no matter what, so we can always switch to pathlib later if we want. I think we should move forward with this as-is.

**Comment by eurunuela** [comment]
Alright, let's move forward with what we have!

**Review by eurunuela — APPROVED** [review]
LGTM! Thank you Taylor!

**Comment by tsalo** [comment]
I just need to run the integration test locally. Will merge once that's working.

**Review by eurunuela — APPROVED** [review]

**Comment by tsalo** [comment]
Test is now passing. Merging now.

**Pull request merged**
