### PR TITLE
[REF] Use Python for mask generation

### PR DESCRIPTION
**Pull request by tsalo**
Related to #2.

Changes proposed in this pull request:

- Replace `bet` and `fslmaths`-based masks with `nilearn.masking.compute_epi_mask()`.

### CODE REVIEW

**Comment by tsalo** [comment]
I'm not sure if `compute_epi_mask` is as good as bet, but it seems to work quite well in my experience. The problems here are that (1) when we support native space data, we'll require tissue probably maps in that same space and (2) when we have standard space data, why would we need an EPI-specific mask? We've already got standard space masks, so...

**Comment by eurunuela** [comment]
Regarding the use of `nilearn.masking.compute_epi_mask()`, it seems like it creates a mask that is eroded 1 voxel in comparison with the FSL-generated mask. See the image below (white is FSL, red is nilearn):

Screen Shot 2020-11-06 at 2 26 39 PM

I imagine this may slightly change the results of the ICA, especially if the data shows big fluctuations due to movement. I don't know how big (or small) of an impact it will be because we're taking the motion parameters into account anyway.

> I'm not sure if compute_epi_mask is as good as bet, but it seems to work quite well in my experience. The problems here are that (1) when we support native space data, we'll require tissue probably maps in that same space and (2) when we have standard space data, why would we need an EPI-specific mask? We've already got standard space masks, so...

How about we ask the users to input the tissue probability maps and if those are not given we assume the data is in standard space? Of course, we would need to check that the data is in standard step and raise an error if that's not the case.

**Comment by tsalo** [comment]
> How about we ask the users to input the tissue probability maps and if those are not given we assume the data is in standard space? Of course, we would need to check that the data is in standard step and raise an error if that's not the case.

I think we have three possible sets of inputs:

1. Standard space data, in which case we use the predefined edge, CSF, etc. masks.
1. Native space data with tissue probability maps, in which case we derive the masks from the TPMs and do the decomposition in native space.
1. Native space data with transforms to standard space, in which case we can either transform the data to standard space and do everything there (as in version 1), or transform the masks to native space and use those in lieu of custom masks.

If that's a comprehensive list, then we can drop all EPI-based masking from the workflow, rather than trying to replace BET with nilearn.

**Comment by eurunuela** [comment]
Those sound good to me.

Right now we've got number 1. I would now focus on number 2 as that's what we wanted to do in the first place. I would leave number 3 for later.

**Comment by tsalo** [comment]
If we're dropping number 3 (for now), we can drop all of the transforms as well. If you're still working on the `nitransforms` usage, that's fine, but if you have it figured out I think we should move forward with it.

**Comment by eurunuela** [comment]
I still haven't had the time for that. It's been a busy week.

**Comment by tsalo** [comment]
Then let's drop transform support for now. I'll open an issue and close this PR.

**Comment by CesarCaballeroGaudes** [comment]
I also think we should focus on option 2. The original ICA-AROMA already operates in the standard space.

**Comment by CesarCaballeroGaudes** [comment]
In addition, I don't really like the mask definitions in the standard space, because they tend to be larger than necessary and include 1 or 2 voxels far outside of the brain. therefore, I usually like use the EPI mask transformed to standard space, or at least multiplying the standard mask with the one computed for the subject.

**Pull request closed without merging**
